issue #1 - allow review submission without metrics defined
RicardoPBarbosa/interview-tests-reviewer pull request #3
Opened 2023-05-06 13:13 UTC by papeixoto

According to #1 users can't submit a review if there's no metrics defined.

My approach is allowing users to make a review using only final score.

The current behaviour allows users to submit a review without every metric filled (just one needed), so this seems to me like the best behaviour.

2023-05-06 14:18 UTC, RicardoPBarbosa requested changes

2023-05-06 14:18 UTC, RicardoPBarbosa commented on src/pages/Review/components/FinalScore.tsx
> +  console.log("average", average);
```suggestion
```

2023-05-06 17:33 UTC, papeixoto commented on src/pages/Review/components/FinalScore.tsx
> +  console.log("average", average);
fds

2023-05-07 09:09 UTC, RicardoPBarbosa approved these changes

2023-05-07 09:09 UTC, merged